### ISSUE TITLE
Task errors with "Error: Docker build failed with exit code 1"

### ISSUE THREAD

**Issue by GitHubJens** [bacongobbler/azure-blob-storage-upload#16]
![image](https://user-images.githubusercontent.com/30659197/122943909-b53a5500-d377-11eb-936e-9f38dada0633.png)

Build container for action use: '/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0/Dockerfile'.
  /usr/bin/docker build -t 8a33c1:c5dad40c69884b438c28e1a349f6dcdc -f "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0/Dockerfile" "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0"
  Sending build context to Docker daemon  19.97kB
  
  Step 1/11 : FROM microsoft/azure-cli
  manifest for microsoft/azure-cli:latest not found: manifest unknown: manifest unknown
  Warning: Docker build failed with exit code 1, back off 3.877 seconds before retry.
  /usr/bin/docker build -t 8a33c1:c5dad40c69884b438c28e1a349f6dcdc -f "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0/Dockerfile" "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0"
  Sending build context to Docker daemon  19.97kB
  
  Step 1/11 : FROM microsoft/azure-cli
  manifest for microsoft/azure-cli:latest not found: manifest unknown: manifest unknown
  Warning: Docker build failed with exit code 1, back off 2.487 seconds before retry.
  /usr/bin/docker build -t 8a33c1:c5dad40c69884b438c28e1a349f6dcdc -f "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0/Dockerfile" "/home/runner/work/_actions/bacongobbler/azure-blob-storage-upload/v1.0.0"
  Sending build context to Docker daemon  19.97kB
  
  Step 1/11 : FROM microsoft/azure-cli
  manifest for microsoft/azure-cli:latest not found: manifest unknown: manifest unknown
Error: Docker build failed with exit code 1

**Comment by bacongobbler** [comment]
Please use a more up-to-date version of azure-blob-storage-upload which uses the updated reference to `mcr.microsoft.com`. v1.2.0 is the latest version.

In the future, please test using a more up-to-date version before filing an issue.
