### ISSUE TITLE
Output blobs list for composite runs

### ISSUE THREAD

**Issue by brenoalvs** [bacongobbler/azure-blob-storage-upload#18]
Hey @bacongobbler, nice job providing this action! Many thanks!

I had to get one of the uploaded files during the action run to do some extra work. So I added the capability to output the blobs list for usage in composite runs.

I also added some scripts for testing.
I'm sending a PR and I hope you like it

Thank you again!

**Comment by bacongobbler** [comment]
closing as inactive.
