### ISSUE TITLE
Switch to the official Azure CLI Docker image

### ISSUE THREAD

**Issue by idrm** [bacongobbler/azure-blob-storage-upload#27]
Wouldn't using the official Azure CLI Docker image by Microsoft (`mcr.microsoft.com/azure-cli`) be more efficient than installing the CLI inside `entrypoint.sh` on every action run?

**Comment by idrm** [comment]
One potential snag is that the CLI image version has to be specified inside `Dockerfile`, and I haven't yet figured out if it's possible to customize that using an action input param. If it's not, that may be a deal breaker for some of your action's users.

**Comment by bacongobbler** [comment]
Done in v3.0.0.

https://github.com/bacongobbler/azure-blob-storage-upload/releases/tag/v3.0.0
