### ISSUE TITLE
Version management can be improved :)

### ISSUE THREAD

**Issue by lgmorand** [bacongobbler/azure-blob-storage-upload#29]
Hi Matthew :) @bacongobbler 

two issues with the version of the Action

1- On the marketplace: it's still the version 1.1 (https://github.com/marketplace/actions/azure-blob-storage-upload)

2- And the main issue is that you fixed the python issue ([commit](https://github.com/bacongobbler/azure-blob-storage-upload/commit/6438be6074241ff0cb89dac42a415d613d2d0a52)) without publishing a new version. consequence, lot of workflows will break because they use v2.X and not azure-blob-storage-upload@main.

workflow using version: https://github.com/lgmorand/aks-checklist/actions/runs/3355816016
workflow using main: https://github.com/lgmorand/aks-checklist/actions/runs/3355838419

could you publish a new 2.0.1 release please and ideally, on the marketplace too. Thanks

**Comment by isatrio** [comment]
I have the same issue with this

**Comment by bacongobbler** [comment]
v2.0.1 has been released. https://github.com/bacongobbler/azure-blob-storage-upload/releases/tag/v2.0.1

AFAICT I have no control over what versions are available on the marketplace. I will look into whether there's an issue causing that, or something else.

**Comment by bacongobbler** [comment]
Ah. I needed to agree to a new set of terms of agreement before it could be published to the marketplace. Done.
