### ISSUE TITLE
[Feature request] Delete files no more available in repo

### ISSUE THREAD

**Issue by o-l-a-v** [bacongobbler/azure-blob-storage-upload#3]
Would be great to have an option to delete files no more available in the repo. For instance, if you rename a file in the repo, "Azure Blob Storage Upload" does not remove the file in the blob with the old name.

**Comment by bacongobbler** [comment]
This would be great. Do you feel like tackling this?

**Comment by o-l-a-v** [comment]
> This would be great. Do you feel like tackling this?

I'm just a simple PowerShell scripter. But I'd think one could look into az commands for achieving this.

* https://docs.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest

AzCopy has a built in option for this scenario, "sync". But from what I can gather from the documentation ^, the sync command does not work in the same way. So I'd probably compare list of files in source with list of files on destination, foreach file not in source anymore run a ```az storage blob delete```.

**Comment by bacongobbler** [comment]
oh, that's wonderful! Thanks @o-l-a-v. I'll see what I can do.

**Comment by bacongobbler** [comment]
fixed in https://github.com/bacongobbler/azure-blob-storage-upload/commit/9b68613240aad40c44b2883226bcf29958f97ef9. Will release v1.1.0 today :)

**Comment by bacongobbler** [comment]
Phew! Okay, v1.1.0 has been released. Please give it a try and let me know if you run into any issues. Thanks!
