### ISSUE TITLE
Create source direction

### ISSUE THREAD

**Issue by adam-bentley** [bacongobbler/azure-blob-storage-upload#30]
I want to be able to upload all the files in the root of my GitHub repository. I tried setting the source as "/" but I got a lot of docker things in my blob storage bucket. What would the correct value be?

Thanks

**Comment by bacongobbler** [comment]
Can you provide your workflow file?

**Comment by adam-bentley** [comment]
name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          sas_token: ${{ secrets.SASToken }}
          account_name : "spacestationdatabase"
          container_name: "spacestation-database"
          source_dir: _dist // Also tried "/"
          overwrite: 'true'

**Comment by bacongobbler** [comment]
Have you tried referring to the current directory with the dot operator (“.”)? Most tools use that to refer to the current directory.

```
source_dir: “.”
```

**Comment by bacongobbler** [comment]
The first example in the README demonstrated how to use the pattern match flag to match on certain file types. The Azure CLI docs may provide more examples than what I provided here, which you can pass through via the extra_args field.
