### ISSUE TITLE
Node12 deprecated issue

### ISSUE THREAD

**Issue by error0327** [bacongobbler/azure-blob-storage-upload#32]
Hi , 

i am getting the below Warning when using : bacongobbler/azure-blob-storage-upload@main
is there anyway to fix that ?

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

![image](https://github.com/bacongobbler/azure-blob-storage-upload/assets/9671558/7d0fb96b-8976-482e-88db-26de834dfb6e)

**Comment by bacongobbler** [comment]
Can you please provide the YAML file?
