### ISSUE TITLE
setting $INPUT_CONNECTION_STRING

### ISSUE THREAD

**Issue by dev-michael-schmidt** [bacongobbler/azure-blob-storage-upload#36]
Hi, I'm new to GitHub actions.  I am happy to find this workflow because it does exactly what I need, and I'm not sure how to set this value:

$INPUT_CONNECTION_STRING

I've set this env var in my `.zshrc`, copying from the Access Keys -> connection string, in my storage account.  I get the error that it's not supplied (and sas).  I've looked at the `entrypoint.sh` script and am still confused.  Can you help me, please?

**Comment by bacongobbler** [comment]
Hi @dev-michael-schmidt. Have you read the README? It describes how to use this action, including how to supply a connection string. See https://github.com/bacongobbler/azure-blob-storage-upload?tab=readme-ov-file#example for an example.

**Comment by dev-michael-schmidt** [comment]
I think what I'm asking is pretty dumb and unrelated this code/readme.  This is the first Action I'd like to use.  I think I'm asking how I define a secret

**Comment by bacongobbler** [comment]
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository
