### ISSUE TITLE
Ignore .git and .github directories

### ISSUE THREAD

**Issue by dvinales** [bacongobbler/azure-blob-storage-upload#5]
Hi,
Thanks for your useful Github action!! I have a question: there is a direct way to ignore these directories with the extra_args? or I necessary to do an extra step copying only the files necessaries to a folder?
Regards,
Danton

**Comment by dvinales** [comment]
Don't worry I resolve this with run: rm -rf .git .github
thanks!

**Comment by bacongobbler** [comment]
You can also use the `--pattern` flag to Only include certain file extensions, like `*.zip`.
