### ISSUE TITLE
bug: sync enabled by default

### ISSUE THREAD

**Issue by bacongobbler** [bacongobbler/azure-blob-storage-upload#6]
After merging the sync flag functionality in https://github.com/bacongobbler/azure-blob-storage-upload/commit/9b68613240aad40c44b2883226bcf29958f97ef9, if the flag is not set in the workflow yaml file, the sync flag is enabled. Setting `sync: false` works around this, however it would be better to disable sync by default. That way files are preserved between uploads.

**Comment by hayer** [comment]
Can confirm. A fix would be great, but the workaround is quite simple.

**Comment by bacongobbler** [comment]
`sync` is now required as of #10. Therefore each user must opt into enabling or disabling the sync flag which resolves this issue.
