### ISSUE TITLE
Add Windows runner support.

### ISSUE THREAD

**Issue by LanceMcCarthy** [bacongobbler/azure-blob-storage-upload#9]
Currently, this action only works in Linux runners. I have been able to use the Azure SDK itself in a Windows Action, see https://github.com/LanceMcCarthy/Action-AzureBlobUpload. 

However, mine is a [JavaScript-based Action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) using TypeScript, so I'm not sure how to set [a Docker container-based Action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) to work on a Windows runner. I am not yet sure this is even possible as I cannot find any Actions documentation on the topic.

 If it is possible, please point me to the docs and I will open a Pull Request in this repo to add the support. 

## Problem

If you run it in an Action with `windows-latest` (or other windows-based runner), you will recieve the following error:

![image](https://user-images.githubusercontent.com/3520532/89713117-8b489180-d963-11ea-8f47-ad47a01cdee1.png)

## Solution Proposal

Add Windows as a `runs-on` option.

**Comment by LanceMcCarthy** [comment]
Closing this as I have written and published a Windows-supported general purpose uploader 

https://github.com/marketplace/actions/azure-blob-upload

**Comment by bacongobbler** [comment]
I was away for the weekend. Why would you open a PR, then close it and fork the project without giving me an opportunity to discuss?

I would’ve happily accepted a PR to switch over to typescript.

**Comment by LanceMcCarthy** [comment]
Hi Matthew, 

Please accept my sincere apologies for any confusion or appearance of hostility. I wasn't trying to be combative by quickly closing it as I opened this Issue before I built the Action and was going to wait until we could fix the underlying problem.

However, after researching more, I found that the core problem was it being a Docker container, so there was nothing you could really do about it. So instead of asking you to fundamentally change the Action (asking you to switch from Docker to Typescript is a big ask).

Since I already have lots of experience with the Azure Storage APIs (albeit in .NET), I decided it was worth learning how to build an Action anyways. I started dev on Friday and finished it on Saturday (which was when I closed this).


Regarding Duplicate Functionality

I agree that having two Actions that do the same thing may lead to confusion. However, I am in the process of adding very specific Microsoft Store and Side-Load distribution features to mine (it will be specific to WPF and UWP apps). This way there is only a small overlap, similar to the existing Azure Blob Actions.
